version: "2"
services:
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    links:
      - currency
      - currencyslow
      - statsd
    environment:
      - MODE
      - SERVERS
  currencyslow:
    build: 
      context: ./currency
      dockerfile: Dockerfile
    ports:
      - "9091:9091"
    environment:
      - SLEEP_TIME
  currency:
    build: 
      context: ./currency
      dockerfile: Dockerfile
    ports:
      - "9092:9091"
  prometheus:
    image: prom/prometheus
    links:
      - statsd
    volumes: 
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9000:9090"
  statsd:
    image: prom/statsd-exporter
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    links:
      - prometheus
