global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
# The job name assigned to scraped metrics by default.
- job_name: statsd
  
  static_configs:
  - targets: ['statsd:9102']
  
- job_name: 'prometheus'
  static_configs:
  - targets: ['localhost:9090']
